version: '3.1'
services:
  db:
    image: mysql
    volumes:
        - mysql-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: libp2p
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: libp2p_rendezvous_db
    ports:
      - "3306:3306"
volumes:
  mysql-db:
