# Derived from official mysql image (our base image)
FROM mysql

# Add env variables
ENV MYSQL_DATABASE libp2p-rendezvous
ENV MYSQL_ROOT_PASSWORD=my-secret-pw
ENV MYSQL_USER=vsantos
ENV MYSQL_PASSWORD=my-secret-pw

EXPOSE 3306
