'use strict'

exports.codes = {
  INVALID_NAMESPACE: 'ERR_INVALID_NAMESPACE',
  INVALID_TTL: 'ERR_INVALID_TTL',
  INVALID_MULTIADDRS: 'ERR_INVALID_MULTIADDRS',
  NO_CONNECTED_RENDEZVOUS_SERVERS: 'ERR_NO_CONNECTED_RENDEZVOUS_SERVERS'
}
