version: '3.2'
services:
  db:
    image: mysql:8
    volumes:
        - mysql-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=libp2p_rendezvous_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  server:
    image: libp2p-rendezvous
    volumes:
      - ./id.json:/etc/opt/rendezvous/id.json
    ports:
      - "8000:8000"
      - "8003:8003"
      - "15003:15003"
    restart: always
    environment:
      - DATASTORE_PASSWORD=my-secret-pw
      - DATASTORE_DATABASE=libp2p_rendezvous_db
      - DATASTORE_HOST=db
      - PEER_ID=/etc/opt/rendezvous/id.json
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql-db: